pretrained_model: openai/whisper-large-v3
mlflow_experiment_name : stt-whisper

use_peft: False
lora_config:
    r: 32
    lora_alpha: 64
    target_modules: ["q_proj", "v_proj"]
    lora_dropout: 0.05
    bias: "none"

training_args:
    output_dir: whisper-large-v3-multilingual
    per_device_train_batch_size: 2
    per_device_eval_batch_size: 2
    gradient_accumulation_steps: 4  # increase by 2x for every 2x decrease in batch size
    learning_rate: 1.0e-5
    warmup_steps: 500
    max_steps: 7500
    gradient_checkpointing: False
    gradient_checkpointing_kwargs:
      use_reentrant: False
    fp16: False
    bf16: True
    eval_strategy: steps
    predict_with_generate: True
    generation_max_length: 200
    save_steps: 250
    eval_steps: 250
    logging_steps: 50
    load_best_model_at_end: True
    metric_for_best_model: loss
    greater_is_better: False
    push_to_hub: True
    hub_model_id: jq/whisper-large-v3-salt-plus-xog-myx-kin-swa
    save_total_limit: 2
    
train:
    download_datasets_in_parallel: True
    datasets:
        - path: gcs://sunflower-data/speech/lug_commonvoice/dev/*.parquet
    source:
      type: speech
      language: [lug]
      preprocessing:
        - set_sample_rate:
            rate: 16_000
        - normalize_audio     
    target:
      type: text
      preprocessing:
        - ensure_text_ends_with_punctuation
      language: [lug]
    shuffle: True
validation:
    datasets:
        - path: gcs://sunflower-data/speech/lug_commonvoice/dev/*.parquet
    source:
      type: speech
      language: [lug]
      preprocessing:
        - set_sample_rate:
            rate: 16_000
        - normalize_audio  
    target:
      type: text
      language: [lug]